services:
  - type: web
    name: paperclip-ai
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: PAPERCLIP_ONBOARDING_COMPLETED
        value: "true"
      - key: PAPERCLIP_DATABASE_MIGRATIONS
        value: "run"
      - key: PAPERCLIP_AUTH_DISABLE_SIGN_UP
        value: "false"
      - key: DATABASE_URL
        value: "postgresql://postgres.ambbmqidlapqnyzhdhta:flJuWsmL8FoYdzhD@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      - key: PAPERCLIP_DATABASE_URL
        value: "postgresql://postgres.ambbmqidlapqnyzhdhta:flJuWsmL8FoYdzhD@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      - key: PAPERCLIP_PUBLIC_URL
        value: "https://paperclip-tqqe.onrender.com"
      - key: BETTER_AUTH_URL
        value: "https://paperclip-tqqe.onrender.com"
    dockerCommand: pnpm start
